# Generated by Django 5.0.4 on 2024-04-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='organizations',
            field=models.ManyToManyField(blank=True, null=True, to='organization_manager.organization'),
        ),
    ]
