# Generated by Django 5.0.4 on 2024-04-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_manager', '0003_household_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(related_name='members_of_household', to='organization_manager.person'),
        ),
        migrations.AlterField(
            model_name='household',
            name='organizations',
            field=models.ManyToManyField(to='organization_manager.organization'),
        ),
    ]
