# Generated by Django 5.0.4 on 2024-04-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_manager', '0004_alter_household_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='household_name',
            field=models.CharField(default="<django.db.models.fields.related.ForeignKey>'s Household", max_length=80),
        ),
    ]
