# Generated by Django 5.0.4 on 2024-04-22 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_manager', '0005_household_household_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='household_name',
        ),
        migrations.RemoveField(
            model_name='household',
            name='members',
        ),
    ]
