# Generated by Django 5.0.4 on 2024-04-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_manager', '0007_alter_household_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='organizations',
        ),
        migrations.AddField(
            model_name='organization',
            name='member_households',
            field=models.ManyToManyField(blank=True, to='organization_manager.household'),
        ),
    ]
