# Generated by Django 5.0.4 on 2024-04-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_manager', '0009_alter_person_email_alter_person_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='household_name',
            field=models.CharField(default='self.household_ID', max_length=20),
        ),
    ]
