# Generated by Django 5.0.4 on 2024-04-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_manager', '0011_alter_household_household_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='household_name',
            field=models.CharField(default=models.AutoField(primary_key=True, serialize=False), max_length=20),
        ),
    ]
