# Generated by Django 5.0.4 on 2024-04-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_manager', '0013_alter_household_household_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='household',
            new_name='house',
        ),
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='organization_manager.person'),
        ),
    ]
