# Generated by Django 5.0.4 on 2024-04-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_manager', '0015_alter_person_email_alter_person_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(blank=True, to='organization_manager.person'),
        ),
    ]
